# Sveltia CMS configuration

# This is where we configure the CMS repo and its collections and fields
# Sveltia CMS generally follows the Decap CMS configuration spec
# Decap CMS docs: https://decapcms.org/docs/intro/
# Sveltia CMS docs: https://github.com/sveltia/sveltia-cms#features

# Enter your GitHub repo path and branch (defaults to master)
backend:
  name: github
  repo: robindotis/robin.is
  branch: master
  base_url: https://sveltia-cms-auth.robinmassart.workers.dev/

# The folder used to store uploaded images
media_folder: "assets/images"

# The CMS collections and their fields
collections:
  - name: "blog"
    label: "Posts"
    label_singular: "Post"
    folder: "posts"
    create: true
    slug: "{{year}}/{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"], hint: "Enter tags separated by a comma" }
      - { label: "Body", name: "body", widget: "markdown", hint: "Plain text, Markdown, and HTML formatting is supported. See the Markdown cheat sheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" }
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "hidden" }
      - label: "Navigation"
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string", hint: "A unique string for your navigation item, typically the page slug." }
          - { label: "Title", name: "title", widget: "string", hint: "The visible title of the navigation item." }
          - { label: "Order", name: "order", widget: "number", default: 999, hint: "Set a number between 0 and 999 to set the display order of your navigation item." }
      - { label: "Body", name: "body", widget: "markdown", hint: "Plain text, Markdown, and HTML formatting is supported. See the Markdown cheat sheet: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" }
  - name: "settings"
    label: "Settings"
    icon: "settings"
    extension: "yml"
    format: "yml"
    files:
      - file: "_data/settings.yml"
        label: "Site Settings"
        name: "site"
        fields:
          - { label: "Site Title", name: "title", widget: "string", hint: "Your site's title, used for branding and SEO." }
          - { label: "Site Description", name: "description", widget: "text", hint: "Your site's description, used for SEO." }
          - { label: "Site URL", name: "url", widget: "string", hint: "Your live site's full URL." }
